apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
    spec:
      containers:
        - name: task-api
          image: kaiburr-task-api:v1
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://root:rootpwd@mongo-mongodb.default.svc.cluster.local:27017/tasksdb?authSource=admin
---
apiVersion: v1
kind: Service
metadata:
  name: task-api-service
spec:
  type: NodePort
  selector:
    app: task-api
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30080
