apiVersion: v1
kind: Service
metadata:
  name: task-api-service
spec:
  selector:
    app: task-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30080
  type: NodePort
